### ISSUE TITLE
No module pyaudio / unable to install pyaudio via pip on Windows native

### ISSUE THREAD

**Issue by estherwang01** [cornell-cup/cs-reminibot#104]
Problem: pip install pyaudio does not work on Windows native + running the GUI results in a no module pyaudio error

Solution (manual installation, not automated yet): 
- Check Python version on your device 
- Download the corresponding .whl file for your Python version/32 vs 64bit from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio  (for example, PyAudio‑0.2.11‑cp38‑cp38‑win_amd64.whl would be used for a device that's 64bit / python 3.8.x)
- Place the .whl in Programs>python>python38 (or whatever you have)>scripts 
- Copy the filepath of the .whl file 
- run `pip install [filepath from above]`

If you run into the issue `filename.whl is not supported wheel on this platform' in the last step above, it is likely the result of one of two issues: 
- The .whl file doesn't match your python version 
- It isn't the right bit number (Note that 32 bit python can be run on 64 bit machines so make sure that isn't causing issues)

**Comment by slawrence100** [comment]
For virtual environments, I found that putting the `.whl` file in the virtual environment's Scripts folder works well - other than that, I was able to get this working on Windows 10 native 🎉
