### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by ashok-arun** [cornell-cup/cs-reminibot#107]
/Users/aarun/Desktop/cs-reminibot/static/gui/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

TypeError: Cannot read property 'length' of undefined
    at processConfiguredOptions (/Users/aarun/Desktop/cs-reminibot/static/gui/node_modules/webpack-cli/bin/utils/convert-argv.js:141:45)

**Comment by kabirwalia8300** [comment]
[Solution by ashok-arun]
https://stackoverflow.com/questions/43589964/how-to-downgrade-version-of-webpack/43590141

you need to use webpack version 3.11.0
